#ifndef _CONSTANTS_H_
    #define _CONSTANTS_H_


#define KEY_ESCAPE 0
#define KEY_UP 1
#define KEY_DOWN 2
#define KEY_LEFT 3
#define KEY_RIGHT 4
#define KEY_SPACE 5
#define KEY_SHIFT 6
#define KEY_CTRL 7
#define KEY_FULLSCREEN 8

#define OBJECT_BACKGROUND_ID 1
#define OBJECT_HERO_ID 2
#define OBJECT_SCORE_ID 3
#define OBJECT_BUS 3001

#define OBJECT_FACING_NORTH 0
#define OBJECT_FACING_SOUTH 1
#define OBJECT_FACING_WEST 2
#define OBJECT_FACING_EAST 3

#define ANIMATION_UPRIGHT 0
#define ANIMATION_WALK_NORTH 1
#define ANIMATION_WALK_SOUTH 2
#define ANIMATION_WALK_WEST 3
#define ANIMATION_WALK_EAST 4
#define ANIMATION_REST_NORTH 5
#define ANIMATION_REST_SOUTH 6
#define ANIMATION_REST_WEST 7
#define ANIMATION_REST_EAST 8
#define ANIMATION_CARRY_NORTH 9
#define ANIMATION_CARRY_SOUTH 10
#define ANIMATION_CARRY_WEST 11
#define ANIMATION_CARRY_EAST 12
#define ANIMATION_CARRY_REST_NORTH 13
#define ANIMATION_CARRY_REST_SOUTH 14
#define ANIMATION_CARRY_REST_WEST 15
#define ANIMATION_CARRY_REST_EAST 16
#define ANIMATION_PISTOL_NORTH 17
#define ANIMATION_PISTOL_SOUTH 18
#define ANIMATION_PISTOL_WEST 19
#define ANIMATION_PISTOL_EAST 20
#define ANIMATION_PISTOL_REST_NORTH 21
#define ANIMATION_PISTOL_REST_SOUTH 22
#define ANIMATION_PISTOL_REST_WEST 23
#define ANIMATION_PISTOL_REST_EAST 24

#define TASK_FIND_BOB 0
#define TASK_FIND_EVA 1
#define TASK_SECURITY_FENCE 2
#define TASK_BUS_PASSENGER 3
#define TASK_BUS 4
#define TASK_HUNT 5
#define TASK_SOCCER 6
#define TASK_SOCCER_BALL 7
#define TASK_FLUNKY_0 8
#define TASK_FLUNKY_1 9

#endif
